name: Deploy Infra and Restore DB

on:
  workflow_dispatch:  # Para ejecución manual

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repositorio
      uses: actions/checkout@v3

    - name: Configurar Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6

    - name: Inicializar Terraform
      working-directory: infra
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      run: terraform init

    - name: Aplicar Terraform
      working-directory: infra
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      run: terraform apply -auto-approve

    - name: Instalar sqlcmd
      run: |
        curl -sSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
        sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
        sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/ubuntu/20.04/prod focal main" > /etc/apt/sources.list.d/mssql-release.list'
        sudo apt-get update
        sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev
        echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
        source ~/.bashrc

    - name: Restaurar base de datos AdventureWorksLT
      shell: pwsh
      run: |
        $sqlServer = "${{ secrets.SQL_SERVER_NAME }}.database.windows.net"
        $user = "${{ secrets.SQL_ADMIN_USER }}"
        $pass = "${{ secrets.SQL_ADMIN_PASS }}"
        $database = "AdventureWorksLT"
        $scriptPath = "database/script.sql"

        /opt/mssql-tools/bin/sqlcmd -S $sqlServer -d $database -U $user -P $pass -i $scriptPath
